(()=>{
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
document.querySelectorAll('[data-carousel]').forEach(root=>{
const track=root.querySelector('.carousel-track'),slides=[...track.children],count=root.querySelector('.slide-count'),play=root.querySelector('[data-play]');let index=0,paused=reduce.matches,hover=false,focus=false,visible=false,timer=0;
function sync(){clearTimeout(timer);play.textContent=paused?'Reproduzir':'Pausar';play.setAttribute('aria-pressed',String(paused));if(!paused&&!hover&&!focus&&visible&&!document.hidden&&!document.querySelector('dialog[open]'))timer=setTimeout(()=>go(index+1),5000);}
function go(i){index=(i+slides.length)%slides.length;track.scrollTo({left:slides[index].offsetLeft-track.offsetLeft,behavior:reduce.matches?'instant':'smooth'});count.textContent=`${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`;sync();}
root.querySelector('[data-prev]').onclick=()=>{paused=true;go(index-1)};root.querySelector('[data-next]').onclick=()=>{paused=true;go(index+1)};play.onclick=()=>{paused=!paused;sync()};
root.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){hover=true;sync()}});root.addEventListener('pointerleave',()=>{hover=false;sync()});root.addEventListener('focusin',()=>{focus=true;sync()});root.addEventListener('focusout',()=>setTimeout(()=>{focus=root.contains(document.activeElement);sync()},0));track.addEventListener('pointerdown',()=>{paused=true;sync()});track.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();paused=true;go(index+(e.key==='ArrowRight'?1:-1))}});
track.addEventListener('scroll',()=>{index=Math.round(track.scrollLeft/(track.clientWidth+18));index=Math.min(slides.length-1,Math.max(0,index));count.textContent=`${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`},{passive:true});new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync()},{threshold:.2}).observe(root);document.addEventListener('visibilitychange',sync);reduce.addEventListener('change',()=>{paused=reduce.matches;sync()});document.querySelector('#viewer')?.addEventListener('close',sync);sync();
});
const main=document.querySelector('main'),hero=document.querySelector('.hero'),ink=document.querySelector('.site-ink'),reveal=ink.querySelector('.site-ink-reveal'),end=document.querySelector('#contact-title');
let origin=0,length=1,frame=0,prev=0,current=0,fill=0;
function measure(){origin=hero.offsetHeight*.74;length=end.getBoundingClientRect().top+scrollY-main.offsetTop-origin+30;ink.style.top=`${origin}px`;ink.style.height=`${Math.max(1,length)}px`;schedule()}
function update(now){frame=0;const front=scrollY+innerHeight*.55-main.offsetTop-origin;const target=reduce.matches?1:scrollY<2?0:Math.max(0,Math.min(1,front/length));const r=end.getBoundingClientRect();const targetFill=reduce.matches?1:Math.max(0,Math.min(1,(innerHeight*.77-r.top)/(innerHeight*.36)));const ease=1-Math.exp(-(prev?Math.min(64,now-prev):16)/105);prev=now;
if(reduce.matches||scrollY<2){current=target;fill=targetFill}else{current+=(target-current)*ease;fill+=(targetFill-fill)*ease}if(Math.abs(current-target)<.0001)current=target;if(Math.abs(fill-targetFill)<.0001)fill=targetFill;reveal.style.clipPath=`inset(0 0 ${100-current*100}% 0)`;reveal.style.setProperty('--front',`${current*100}%`);reveal.style.maskImage=current===1?'none':'';end.style.setProperty('--fill',`${fill*100}%`);
if(current!==target||fill!==targetFill)frame=requestAnimationFrame(update);else prev=0;}
function schedule(){if(!frame)frame=requestAnimationFrame(update)}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',measure);addEventListener('load',measure);reduce.addEventListener('change',measure);document.fonts.ready.then(measure);measure();
})();
